# Error messages for CRUDBase
ERR_OBJECT_NOT_FOUND_ID = "'{}' WITH ID '{}' NOT FOUND!"
ERR_NAME_BUSY = "'{}' NAME '{}' IS BUSY!"

# Error messages for reservations_validator
ERR_DATETIME_FORMAT = "TIMESTAMP MUST BE WITHOUT TIME ZONE"
ERR_RESERVATION_DATETIME = "ON THIS TIME TABLE IS BUSY"
ERR_RESERVATION_OVERLAPPING = "RESERVATION OVERLAPPING: {}"
ERR_RESERVATION_EXIST = "TABLE HAVE RESERVATIONS!"

# Busy reservation message template
RESERVATION_BUSY = "RESERVATION FOR {} FROM {} TO {}"
